### PR TITLE
회원 프로필 조회 controller 구현 

### PR DESCRIPTION
**Pull request by younghoondoodoom**

### CODE REVIEW

**Comment by naekang** [comment]
|File|Coverage [41.51%]|:x:|
|:-|:-:|:-:|
|[MemberController.java](https://github.com/Gaethering/Gaethering-Server/blob/69912ceaac8e6b1cd5730f85f308d2c195e738e8/src%2Fmain%2Fjava%2Fcom%2Fgaethering%2Fgaetheringserver%2Fmember%2Fcontroller%2FMemberController.java)|41.51%|:x:|

|Total Project Coverage|43.76%|:x:|
|:-|:-:|:-:|

**Comment by naekang** [comment]
|File|Coverage [41.51%]|:x:|
|:-|:-:|:-:|
|[MemberController.java](https://github.com/Gaethering/Gaethering-Server/blob/b395aab0304fc92366dcee1c4ffcd493d4de84ef/src%2Fmain%2Fjava%2Fcom%2Fgaethering%2Fgaetheringserver%2Fmember%2Fcontroller%2FMemberController.java)|41.51%|:x:|

|Total Project Coverage|43.77%|:x:|
|:-|:-:|:-:|

**Comment by naekang** [comment]
수고하셨습니다! 😀

**Review by bokyung95 — COMMENTED** [review]
고생하셨습니다!
테스트 코드 작성하는 방법 배우고 갑니다!

**Comment by naekang** [comment]
|File|Coverage [41.51%]|:x:|
|:-|:-:|:-:|
|[MemberController.java](https://github.com/Gaethering/Gaethering-Server/blob/b01f6db8c3504a10bd5ced30306034ce8cbcf562/src%2Fmain%2Fjava%2Fcom%2Fgaethering%2Fgaetheringserver%2Fmember%2Fcontroller%2FMemberController.java)|41.51%|:x:|

|Total Project Coverage|45.76%|:x:|
|:-|:-:|:-:|

**Pull request merged**
